### ISSUE TITLE
Add a basic footer to the site

### ISSUE THREAD

**Issue by alecrem** [asobiya/asobiya-website#2]

**Comment by Pulkitxm** [comment]
Can I get assigned ?

**Comment by alecrem** [comment]
Thank you for commenting, @Pulkitxm, and I'm sorry that contributing to this repo has been so unclear so far.

To this point, we only assign issues via Dework, and only token holders in our community can apply to the tasks there. If you like what we want to do, please interact with us more on Twitter or Discord.
