### ISSUE TITLE
storeページの追加

### ISSUE THREAD

**Issue by shokaji** [asobiya/asobiya-website#24]
・おおむねwebsiteが出来上がったら着手するような予定で。
・トークンでグッズなどを購入できるページ

**Comment by alecrem** [comment]
これは、手動でうる感じでしょうか？

でしたら、穏やかにcontentsラベルでいいと思います。

もしコントラクトが必要なイメージでしたら、先に達成しなければならないタスクがまだいくつか登録されていないと思います・・・

**Comment by shokaji** [comment]
すいません、コントラクトが必要なイメージになりそうです!
とりあえずページだけ追加しとくというイメージのイシューでした!
一旦クローズしときます!

**Comment by alecrem** [comment]
やりたいならopenでいいと思いますよ！すぐにはできないけど。

**Comment by shokaji** [comment]
了解です。とりあえずindexとmembersページが大体できあがったらopenにしたいと思います。
