### ISSUE TITLE
membersカードの黄色い背景をなんとかする

### ISSUE THREAD

**Issue by alecrem** [asobiya/asobiya-website#48]
一人ずつ違う画像？デフォルト画像？単色？
要議論。

**Comment by shokaji** [comment]
デフォルト画像は何か1つ設定しておいて、希望する人は自分の好きな画像をサイズ指定して用意してもらうというのはどうでしょうか? 一つの提案ですが。ただバラバラだとメンバー増えてくると重くなるかもしれませんよね。。。

そう考えると統一したほうが良いでしょうか?

**Comment by sushi-yam** [comment]
もし統一するなら、私でもできそうなのでやってみたいです。

**Comment by sushi-yam** [comment]
メンバーページのメンバーカードの上の部分の黄色のシマシマを削除して、グラディエーションカラーを表示。
白背景と黒背景でグラディエーションの色合いを変えています。
後で画像を表示するかもしれないので、黄色のしましま画像のコードはコメントアウトしてあります。
