### ISSUE TITLE
ウェブサイトでasobiyaトークンの残高が確認できるように

### ISSUE THREAD

**Issue by alecrem** [asobiya/asobiya-website#8]

**Comment by shokaji** [comment]
これやってみたいのですが、大まかにどのような流れでやっていけばよさそうでしょうか?

**Comment by alecrem** [comment]
週末から下調べしているレベルで、説明まではできないです。
動き始めたら、子タスクをissueとして登録しようと思っていたのですが、いかがでしょうか？

今までHenkakuで使ってきたwagmiより、最近Ryomaさんがmintrallyで導入したthreewebを初めて使ってみたいと思ったのですが、いかがでしょうか？
この辺りから勉強中です https://portal.thirdweb.com/auth/server-frameworks/next
